# 数据库配置信息，配置映射的mysql数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fly_etl?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# 生成文件路径，对应每层包路径(绝对路径)
package:
  path:
    entity: D:\workspace\BaseStructure1\src\main\java\base\entity
    dao: D:\workspace\BaseStructure1\src\main\java\base\dao
    service: D:\workspace\BaseStructure1\src\main\java\base\service
    service-impl: D:\workspace\BaseStructure1\src\main\java\base\service\impl
    controller: D:\workspace\BaseStructure1\src\main\java\base\controller
    result-value: D:\workspace\BaseStructure\src\main\java\base\common\entity
    result-builder: D:\workspace\BaseStructure\src\main\java\base\common

# 生成类文件开关，控制是否生成该层文件，true为生成，false为不生成
make:
  entity: true
  dao: true
  service: true
  service-impl: true
  controller: true

# 是否全量生成（true:生成该数据库所有表对应的类，false:生成该数据库指定的表对应的类）
number:
  all-table: false
  # 当all-table参数为false时，指定生成的表名
  table-name: statistics_schedule

# 作者信息，默认为系统用户名称
maker:
  author: shalt gao
